### ISSUE TITLE
É compatível com quais versões de Opencart?

### ISSUE THREAD

**Issue by smfsoft** [plugg-to/pluggto-opencart#1]
É compatível com quais versões de Opencart?

**Comment by reginaldojunior** [comment]
Com as 1.5.x, 2.x...

A versão 3 ainda não temos compatibilidade. 

Releases mais recentes:

2.3.x: https://github.com/plugg-to/pluggto-opencart/releases/tag/1.2.4_2.3-oc-version
2.2.x: https://github.com/plugg-to/pluggto-opencart/releases/tag/2.1.1_2.0-oc-version
1.5.x: https://github.com/plugg-to/pluggto-opencart/releases/tag/2.0.1_1.5-oc-version
